---
- hosts: all
  become: true
  gather_facts: yes
  tasks:
  - name: install httpd
    action: yum name=httpd state=present
  - name: restart httpd
    action: service name=httpd state=started
  - name: creating source code
    file:
      path: "/var/www/html/index.html"
      state: touch
  - name: enter the content
    copy:
      dest: "/var/www/html/index.html"
      content: 1
        <h1>this is my website</h1>
