---
- name: Install Apache Tomcat10 using ansible
  hosts: all
  remote_user: ansible
  become: true
  tasks:
    - name: Update the System Packages
      command: yum update -y

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      command: amazon-linux-extras install java-openjdk11 -y

    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
    - name: installing packages
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        dest: /opt
        mode: 0755
    - name: download & unarchive tomcat10 
      unarchive:
        src: /opt/apache-tomcat-10.1.6.tar.gz
        dest: /opt
        remote_src: yes
        extra_opts: [--strip-components=1]
    - name: Change ownership of tomcat directory
      file:
        path: /opt/apache-tomcat-10.1.6
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory


    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
